server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/test_demo}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:272004}
    username: ${DBMS_USERNAME:root}
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
